### ISSUE TITLE
Image upscaling /resizing

### ISSUE THREAD

**Issue by Roshankurikkal** [AllInOneYT/react-native-thermal-printer#17]
As the title suggested , is it possible to resize or upscale image

**Comment by AllInOneYT** [comment]
That's a good idea, but I don't think it should be a part of printer library. Another library maybe?

**Comment by Roshankurikkal** [comment]
how about changing the default size of image , is that possible ?

**Comment by richardfariax** [comment]
Utilize **react-native-image-resizer**
