### ISSUE TITLE
Can't start project 

### ISSUE THREAD

**Issue by Lenny4** [AllInOneYT/react-native-thermal-printer#20]
Hello @AllInOneYT ,

I was starting to work on https://github.com/AllInOneYT/react-native-thermal-printer/issues/19 and in the [README](https://github.com/AllInOneYT/react-native-thermal-printer/blob/main/CONTRIBUTING.md#development-workflow) it says:

> To start the packager:
> 
> ```sh
> yarn example start
> ```

Here is my output when I launch `yarn example start`:
```
yarn run v1.22.17
$ yarn --cwd example start
error Command "start" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

When I run `yarn example` I have no errors:
```
yarn run v1.22.17
$ yarn --cwd example
[1/4] Resolving packages...
success Already up-to-date.
$ bob build
ℹ Building target commonjs
ℹ Cleaning up previous build at lib/commonjs
ℹ Compiling 1 files in src with babel
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
✔ Wrote files to lib/commonjs
ℹ Building target module
ℹ Cleaning up previous build at lib/module
ℹ Compiling 1 files in src with babel
✔ Wrote files to lib/module
ℹ Building target typescript
ℹ Cleaning up previous build at lib/typescript
ℹ Generating type definitions with tsc
✔ Wrote definition files to lib/typescript
Done in 3.02s.
```

Do you know why ?

**Comment by Lenny4** [comment]
@AllInOneYT I'm still waiting for an answer.

**Comment by AllInOneYT** [comment]
> @AllInOneYT I'm still waiting for an answer.

Thank you for your patience. I apologize for the delay. I have no idea about that command, It was an automatically generated README. the way I test it was to run `yarn test && yarn typescript && yarn lint && yarn prepare && yarn pack` and install the generated `.tgz` file directly to my existing application

**Comment by AllInOneYT** [comment]
Oh I see. This repo does not contain example project. There should be `example` folder containing a test project and the command failed because the project does not exist.
