### ISSUE TITLE
hello sir, iam running ./gradlew assembleRelease error

### ISSUE THREAD

**Issue by Fharhanamrin** [AllInOneYT/react-native-thermal-printer#30]
* What went wrong:
Execution failed for task ':app:mergeDexRelease'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.DexMergingTaskDelegate
   > There was a failure while executing work items
      > A failure occurred while executing com.android.build.gradle.internal.tasks.DexMergingWorkAction
         > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
           Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
           Type com.reactnativethermalprinter.BuildConfig is defined multiple times: /Users/smi/Documents/appBelajar/reactnativethermalprinter/node_modules/react-native-thermal-printer/android/build/.transforms/892d74cb21fa1b6f184d63ce03b459ff/transformed/classes/classes.dex, /Users/smi/Documents/appBelajar/reactnativethermalprinter/android/app/build/intermediates/project_dex_archive/release/out/com/reactnativethermalprinter/BuildConfig.dex

**Comment by AllInOneYT** [comment]
try to `Build -> Rebuild Project`

**Comment by AllInOneYT** [comment]
try to clean and rebuild

**Comment by Fharhanamrin** [comment]
done sir
I don't know, yesterday I had an issue in a new React Native project, but when I created a new one in React Native 0.67, now it works sir, thank you
