### ISSUE TITLE
different font size

### ISSUE THREAD

**Issue by vikrammani-t2s** [AllInOneYT/react-native-thermal-printer#32]
``is that possible to change the font  size like 12,14,18
eg :
`"[C]<u><font size='big'>ORDER N°045</font></u>\n" +
 like this
"[C]<u><font size=14>ORDER N°045</font></u>\n" +`

**Comment by AllInOneYT** [comment]
for now the available sizes are listed here: [font size](https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/tree/3.0.1#size). Feel free to contribute to the [original library](https://github.com/DantSu/ESCPOS-ThermalPrinter-Android) :)
