### ISSUE TITLE
How can I play the printer sound

### ISSUE THREAD

**Issue by JelouSoft** [AllInOneYT/react-native-thermal-printer#34]
Hey, I can't find how to play the beep sound while printing.

Any solution?

**Comment by AllInOneYT** [comment]
adding this two lines works for me 
```java
printerConnection.write(new byte[]{27, 66, 2, 1});
printerConnection.send(0);
```

**Comment by JelouSoft** [comment]
Excuse me, where can I add these lines?

**Comment by AllInOneYT** [comment]
whetther here before printing

https://github.com/AllInOneYT/react-native-thermal-printer/blob/9d5df0358f7e2306f25f730b334ce14743b091b5/android/src/main/java/com/reactnativethermalprinter/ThermalPrinterModule.java#L182

or here after printing
https://github.com/AllInOneYT/react-native-thermal-printer/blob/9d5df0358f7e2306f25f730b334ce14743b091b5/android/src/main/java/com/reactnativethermalprinter/ThermalPrinterModule.java#L190

or both

The reason it is not included in the library is that printer sound is originally intended for warnings and errors.

**Comment by JelouSoft** [comment]
Thank u, it works!!!

**Comment by thanhchuongbmd** [comment]
> adding this two lines works for me
> 
> ```java
> printerConnection.write(new byte[]{27, 66, 2, 1});
> printerConnection.send(0);
> ```

This sound is short. What the params for sound longer or volume greater?

**Comment by AllInOneYT** [comment]
> > adding this two lines works for me
> > ```java
> > printerConnection.write(new byte[]{27, 66, 2, 1});
> > printerConnection.send(0);
> > ```
> 
> This sound is short. What the params for sound longer or volume greater?

you cannot change the volume of the sound as far as I know. refer to this issue https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/issues/142 for more information

**Comment by thanhchuongbmd** [comment]
> > > adding this two lines works for me
> > > ```java
> > > printerConnection.write(new byte[]{27, 66, 2, 1});
> > > printerConnection.send(0);
> > > ```
> > 
> > 
> > This sound is short. What the params for sound longer or volume greater?
> 
> you cannot change the volume of the sound as far as I know. refer to this issue [DantSu/ESCPOS-ThermalPrinter-Android#142](https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/issues/142) for more information

Thank you!
