### ISSUE TITLE
Datamax oniel 4te bluetooth printing issue

### ISSUE THREAD

**Issue by Sameerawan** [AllInOneYT/react-native-thermal-printer#37]
Hello,

I am facing an issue when I print the receipt from my thermal printer it's showing t on the start and end of every string. I have printed sample bill but it's printer t before and after it. What can be the solution? I have attached the screenshots.

![IMG-20220913-WA0010](https://user-images.githubusercontent.com/23479835/190024518-a032518a-97ba-418e-ae38-968273653d7d.jpg)
![IMG-20220913-WA0008](https://user-images.githubusercontent.com/23479835/190024522-f446e5a9-4151-47ab-bce4-72d8e3bf7bcd.jpg)

**Comment by AllInOneYT** [comment]
I believe you have to match the [config](https://github.com/AllInOneYT/react-native-thermal-printer#available-config) with your printer.

Try to check if the `printerDpi` `printerWidthMM` and `printerNbrCharactersPerLine` match your printer's specification
