### ISSUE TITLE
Can we use it for thermal label printers?

### ISSUE THREAD

**Issue by KannarFr** [AllInOneYT/react-native-thermal-printer#46]
Hi, 

I'm heavily using this for classic thermal printers. And looking for thermal label printers that can be controlled with this library. Any feedback?

**Comment by AllInOneYT** [comment]
We surely can bridge it if the original https://github.com/DantSu/ESCPOS-ThermalPrinter-Android can do so

**Comment by KannarFr** [comment]
I was wrong, globally thermal labels printers are "simple" little printer, so I just have to use react-native-printer. NVM.
