### ISSUE TITLE
Does your package work with Expo?

### ISSUE THREAD

**Issue by gundogdutekin** [AllInOneYT/react-native-thermal-printer#59]
Hello;

Does your package work with Expo? Or does it only work with React Native CLI? I would be very happy if you answer :)

**Comment by AllInOneYT** [comment]
I am not sure about expo. I tried CLI only :)

**Comment by AllInOneYT** [comment]
I believe it works on both

https://github.com/AllInOneYT/react-native-thermal-printer/issues/23#issuecomment-1107850021
